
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-calculator
  labels:
    app: java-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-calculator
  template:
    metadata:
      labels:
        app: java-calculator
    spec:
      containers:
      - name: java-calculator
        image: kowshikrampalli/java-calculator-app:latest
        ports:
        - containerPort: 8090

