pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "kowshikrampalli/java-calculator-app:latest"
        DOCKER_CREDENTIALS_ID = 'dockerhub'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/RampalliKowshik/AWS-Devops-CI-CD-pipeline-Integration.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dir('java-calculator-app') {
                        sh 'docker build -t $DOCKER_IMAGE .'
                    }
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: DOCKER_CREDENTIALS_ID,
                                                 usernameVariable: 'DOCKER_USER',
                                                 passwordVariable: 'DOCKER_PASS')]) {
                    script {
                        sh 'echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin'
                        sh 'docker push $DOCKER_IMAGE'
                    }
                }
            }
        }
    }

    post {
        success {
            echo '✅ Docker Image Built & Pushed Successfully!'
        }
        failure {
            echo '❌ Build Failed!'
        }
    }
}
