
apiVersion: v1
kind: Pod
metadata:
  name: java-calculator-pod
spec:
  containers:
    - name: java-calculator
      image: kowshikrampalli/java-calculator-app:latest
      command: ["/bin/sh", "-c"]
      args: ["while true; do sleep 3600; done"]
  restartPolicy: Always

