
apiVersion: v1
kind: Service
metadata:
  name: java-calculator-service
spec:
  selector:
    app: java-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  type: LoadBalancer

