
apiVersion: v1
kind: Service
metadata:
  name: java-calculator-service
spec:
  selector:
    app: java-calculator-app  # Ensure this matches the pod label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer

